version: '3'
services:
    app:
        image: powermeter
        build:
            dockerfile: docker/Dockerfile
            context: .
        env_file:
            -   ./docker/envs/.django
        ports:
            - "8000:8000"

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data01:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

    kibana:
      image: docker.elastic.co/kibana/kibana:8.10.2
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch

volumes:
  data01:
    driver: local
