version: '3'
services:
    app:
        image: powermeter
        build:
            dockerfile: docker/Dockerfile
            context: .
        env_file:
            -   ./docker/envs/.django
        ports:
            - "8000:8000"
