export USE_DOCKER=False
export PYTHONBREAKPOINT=ipdb.set_trace
export DJANGO_READ_DOT_ENV_FILE=True
export DJANGO_SETTINGS_MODULE=config.settings.local
export DATABASE_URL=sqlite:///db.sqlite
export DJANGO_SECRET_KEY=GshR1eOXSDZRYf37smvAvFxsmBFAzxwpYI2gSyTrK8YtusU6pibIIMZ7jVNLYuwY
export DJANGO_SECURE_SSL_REDIRECT=False
